# Generated by Django 5.1.4 on 2025-01-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('CA', 'Cash')], default='PP', max_length=2),
        ),
    ]
