# Generated by Django 5.1.4 on 2025-01-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_session_cart_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_must_have_customer_or_session',
        ),
    ]
