# Generated by Django 5.1.4 on 2025-01-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_customer_address'),
        ('cart', '0007_remove_cart_cart_must_have_customer_or_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='accounts.customer'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False)), fields=('customer', 'completed'), name='unique_active_customer_cart'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False)), fields=('session_key', 'completed'), name='unique_active_session_cart'),
        ),
    ]
