# Generated by Django 5.1.4 on 2025-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_customer_cart_unique_active_customer_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
