# Generated by Django 5.1.4 on 2025-01-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='last_modified',
        ),
    ]
