# Generated by Django 5.1.4 on 2025-02-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_cart_last_modified'),
        ('products', '0002_product_stock_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ADD', 'Item Added'), ('REMOVE', 'Item Removed'), ('UPDATE', 'Item Updated'), ('CLEAR', 'Cart Cleared')], max_length=6)),
                ('quantity', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cart', 'timestamp'], name='cart_cartev_cart_id_fa5ffc_idx')],
            },
        ),
    ]
