# Generated by Django 5.1.4 on 2025-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_customer_address'),
        ('cart', '0011_cartevent'),
        ('products', '0002_product_stock_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['version'], name='cart_cart_version_06ddd1_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['last_modified'], name='cart_cart_last_mo_277ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['version'], name='cart_cartit_version_8a5457_idx'),
        ),
    ]
