# Generated by Django 5.1.4 on 2025-02-08 13:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cart_last_modified_cart_version_cartitem_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='_subtotal',
            field=models.DecimalField(db_column='subtotal', decimal_places=2, default=Decimal('0.00'), help_text='Subtotal in euros (€)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='_tax',
            field=models.DecimalField(db_column='tax', decimal_places=2, default=Decimal('0.00'), help_text='Tax amount in euros (€)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price in euros (€)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
