# Generated by Django 5.1.4 on 2025-02-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cart__subtotal_alter_cart__tax_and_more'),
        ('products', '0002_product_stock_non_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.product'),
        ),
    ]
