# Generated by Django 5.1.4 on 2025-02-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartevent',
            name='event_type',
            field=models.CharField(choices=[('ADD', 'Item Added'), ('REMOVE', 'Item Removed'), ('UPDATE', 'Item Updated'), ('CLEAR', 'Cart Cleared'), ('EXPIRE', 'Cart Expired')], max_length=6),
        ),
    ]
