# Generated by Django 5.1.4 on 2025-02-08 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cartevent_event_type'),
        ('products', '0002_product_stock_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartevent',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='event_type',
            field=models.CharField(choices=[('ADD', 'Item Added'), ('REMOVE', 'Item Removed'), ('UPDATE', 'Item Updated'), ('CLEAR', 'Cart Cleared'), ('EXPIRE', 'Cart Expired'), ('MERGE', 'Cart Merged')], max_length=6),
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
