# Generated by Django 5.1.4 on 2025-02-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_cartevent_created_at_cartevent_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartevent',
            name='event_type',
            field=models.CharField(choices=[('checkout_started', 'Checkout started'), ('cleared', 'Cart cleared'), ('item_added', 'Item added'), ('item_removed', 'Item removed'), ('quantity_changed', 'Quantity changed'), ('EXPIRE', 'Cart expired'), ('MERGE', 'Cart merged')], max_length=20),
        ),
    ]
