# Generated by Django 5.1.4 on 2025-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_cartevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartevent',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
