# Generated by Django 5.1.4 on 2025-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cartevent_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartevent',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='event_type',
            field=models.CharField(choices=[('cart_created', 'Cart created'), ('checkout_started', 'Checkout started'), ('cleared', 'Cart cleared'), ('item_added', 'Item added'), ('item_removed', 'Item removed'), ('quantity_updated', 'Quantity updated'), ('stock_updated', 'Stock updated'), ('expired', 'Cart expired'), ('merged', 'Cart merged'), ('batch_add', 'Batch items added'), ('batch_update', 'Batch quantities updated')], max_length=20),
        ),
    ]
