# Generated by Django 5.1.4 on 2026-09-30 16:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def mark_existing_orders_as_delivery(apps, schema_editor):
    # Every order created before this migration had a shipping address.
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(address__isnull=False).update(fulfillment_method='delivery')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_session_key"),
        ("orders", "0003_remove_order_positive_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_method",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                default="pickup",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="requested_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_addresses",
                to="accounts.address",
            ),
        ),
        migrations.RunPython(mark_existing_orders_as_delivery, migrations.RunPython.noop),
    ]
