# Generated by Django 5.1.4 on 2026-09-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_checkout_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CC", "Card on pickup/delivery"),
                    ("PP", "PayPal"),
                    ("CA", "Cash on pickup/delivery"),
                ],
                default="PP",
                max_length=2,
            ),
        ),
    ]
