# Generated by Django 5.1.4 on 2026-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_payment_method_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")],
                default="de",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CC", "Card on pickup/delivery"),
                    ("PP", "PayPal"),
                    ("CA", "Cash on pickup/delivery"),
                    ("ST", "Paid online"),
                ],
                default="PP",
                max_length=2,
            ),
        ),
    ]
