# Generated by Django 5.1.4 on 2026-10-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_online_payment_and_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English"), ("ar", "العربية")],
                default="de",
                max_length=8,
            ),
        ),
    ]
