"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Load KEY=VALUE lines from a local .env file without overriding real env vars."""
    if not path.is_file():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


_load_env_file(BASE_DIR / '.env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. '
            'Copy backend/.env.example to backend/.env for local development.'
        )
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')


# Application definition

BACKEND_APPS = [
    'apps.core',
    'apps.accounts',
    'apps.products',
    'apps.cart',
    'apps.orders',
    'apps.content',
    'apps.shop',
    'apps.menuboard',
    'apps.studio',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',  # Swagger UI generation
] + BACKEND_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files and, in production, the built storefront.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Answers in the language the shop sends (Accept-Language: de or en).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'layers.middleware.customer_middleware.CustomerMiddleware',
    'layers.middleware.cart_middleware.CartMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'layers.context_processors.cart_processor.cart_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# SQLite locally. In production either DATABASE_URL or the POSTGRES_*
# settings (as used by docker-compose.yml) point to Postgres.
import dj_database_url  # noqa: E402
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(os.environ.get('DATABASE_CONN_MAX_AGE', '60')),
    )
}
if not os.environ.get('DATABASE_URL') and os.environ.get('POSTGRES_HOST'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ['POSTGRES_HOST'],
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'NAME': os.environ.get('POSTGRES_DB', 'backlover'),
        'USER': os.environ.get('POSTGRES_USER', 'backlover'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'CONN_MAX_AGE': int(os.environ.get('DATABASE_CONN_MAX_AGE', '60')),
    }
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    # Several requests at once (the shop loads cart, products and more in
    # parallel) should wait for each other instead of failing as "locked".
    DATABASES['default'].setdefault('OPTIONS', {}).update({'transaction_mode': 'IMMEDIATE', 'timeout': 20})
    DATABASES['default']['CONN_MAX_AGE'] = 0


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('de', 'Deutsch'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# Opening hours, pickup slots and "today" in the admin follow the shop's clock.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Europe/Berlin')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [path for path in [BASE_DIR / 'static'] if path.is_dir()]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
# Optional: keep uploads (product photos, 3D models) in an S3-compatible
# bucket instead of on the server's disk. Needs `django-storages[s3]`
# (requirements-prod.txt); see DEPLOY.md for the bucket's CORS rule.
if os.environ.get('AWS_STORAGE_BUCKET_NAME'):
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME') or None
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') or None
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'public, max-age=31536000'}

# The built storefront (frontend/dist). WhiteNoise serves its files (/assets,
# /draco, images) straight from this folder; page URLs fall through to
# FRONTEND_INDEX_FILE below. Vite's hashed assets are cached for a year.
WHITENOISE_ROOT = os.environ.get('FRONTEND_DIST_DIR') or None
WHITENOISE_IMMUTABLE_FILE_TEST = r'^.+[.-][0-9a-zA-Z_-]{8,12}\.\w+$'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'  

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'URL_FORMAT_OVERRIDE': None,  # Disable format suffixes
    # Applied only to views that set throttle_scope (ScopedRateThrottle).
    'DEFAULT_THROTTLE_RATES': {
        'password_reset': '5/hour',
        'contact': '10/hour',
        'newsletter': '10/hour',
    },
}

# Swagger settings
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'SECURITY_REQUIREMENTS': [{'Bearer': []}],
}

# CORS settings
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:5173')
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'accept-language',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_DOMAIN = None  # Allow localhost

# CSRF settings
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost:5173')
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # False to allow JavaScript access
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_DOMAIN = None  # Allow localhost
CSRF_COOKIE_SECURE = not DEBUG

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.cart': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'layers.middleware': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Shop settings. Prices are stored and shown including VAT (gross).
from decimal import Decimal  # noqa: E402
VAT_RATE = Decimal(os.environ.get('SHOP_VAT_RATE', '0.19'))
DELIVERY_FEE = Decimal(os.environ.get('SHOP_DELIVERY_FEE', '3.50'))
# Online payment providers need credentials; until configured, only cash
# and card on pickup/delivery are offered.
PAYPAL_ENABLED = _env_bool('SHOP_PAYPAL_ENABLED', False)

# Online payment with Stripe Checkout (cards, Apple Pay, Google Pay and any
# other method switched on in the Stripe dashboard). Offered at checkout
# once the secret key and webhook secret are set; see DEPLOY.md.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_ENABLED = bool(STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET)
# Unpaid online orders give their stock back after this long (Stripe's
# minimum is 30 minutes).
STRIPE_CHECKOUT_MINUTES = max(30, int(os.environ.get('STRIPE_CHECKOUT_MINUTES', '30')))

# Pickup and delivery times offered at checkout (apps/orders/slots.py).
# Days not listed are closed, e.g. "mon-fri 07:00-18:00; sat 08:00-14:00".
SHOP_OPENING_HOURS = os.environ.get('SHOP_OPENING_HOURS', 'mon-fri 07:00-18:00; sat 07:00-14:00; sun 08:00-12:00')
SHOP_SLOT_MINUTES = int(os.environ.get('SHOP_SLOT_MINUTES', '30'))
SHOP_SLOT_DAYS = int(os.environ.get('SHOP_SLOT_DAYS', '7'))
SHOP_PICKUP_LEAD_MINUTES = int(os.environ.get('SHOP_PICKUP_LEAD_MINUTES', '60'))
SHOP_DELIVERY_LEAD_MINUTES = int(os.environ.get('SHOP_DELIVERY_LEAD_MINUTES', '120'))
# Orders per slot before it is shown as taken (0 = no limit).
SHOP_SLOT_CAPACITY = int(os.environ.get('SHOP_SLOT_CAPACITY', '0'))

# Shown in page titles, share previews and structured data (apps/core/seo.py).
SHOP_NAME = os.environ.get('SHOP_NAME', 'Backlover')
SHOP_STREET = os.environ.get('SHOP_STREET', 'Friedrichstraße')
SHOP_CITY = os.environ.get('SHOP_CITY', 'Berlin')

# Path to the built storefront (frontend/dist/index.html). When set, Django
# serves it for storefront URLs with each page's meta tags filled in.
FRONTEND_INDEX_FILE = os.environ.get('FRONTEND_INDEX_FILE', '')

# The storefront has its own /admin, so Django's admin lives elsewhere.
DJANGO_ADMIN_PATH = os.environ.get('DJANGO_ADMIN_PATH', 'django-admin/').strip('/') + '/'

# Email (password reset, contact form). Printed to the console unless an
# SMTP server is configured.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@localhost')
SHOP_NOTIFICATION_EMAIL = os.environ.get('SHOP_NOTIFICATION_EMAIL', '')
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ['EMAIL_HOST']
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# HTTPS hardening outside local development
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Error reports (optional): set SENTRY_DSN. Needs `sentry-sdk`
# (requirements-prod.txt). Personal data is not sent.
if os.environ.get('SENTRY_DSN'):
    import sentry_sdk  # noqa: E402
    sentry_sdk.init(
        dsn=os.environ['SENTRY_DSN'],
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0')),
        send_default_pii=False,
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
