# Generated by Django 5.1.4 on 2026-10-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClosingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="Empty: closed on the start day only",
                        null=True,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=150)),
                ("label_en", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("legal_name", models.CharField(blank=True, max_length=150)),
                ("owner", models.CharField(blank=True, max_length=150)),
                ("street", models.CharField(blank=True, max_length=150)),
                ("house_number", models.CharField(blank=True, max_length=20)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("transit", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("vat_id", models.CharField(blank=True, max_length=50)),
                ("register", models.CharField(blank=True, max_length=150)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Receives new orders and contact messages",
                        max_length=254,
                    ),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("pickup_enabled", models.BooleanField(default=True)),
                ("delivery_enabled", models.BooleanField(default=True)),
                (
                    "delivery_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pickup_lead_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "delivery_lead_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("slot_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("slot_days", models.PositiveIntegerField(blank=True, null=True)),
                ("slot_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("announcement", models.CharField(blank=True, max_length=300)),
                ("announcement_en", models.CharField(blank=True, max_length=300)),
                ("announcement_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shop settings",
                "verbose_name_plural": "Shop settings",
            },
        ),
    ]
