# Generated by Django 5.1.4 on 2026-10-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0007_english_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=110, unique=True)),
                ("code", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Shown at /menu-board without a name"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("columns", "Feature and columns"),
                            ("grid", "Photo grid"),
                            ("list", "Classic list"),
                            ("spotlight", "One product at a time"),
                        ],
                        default="columns",
                        max_length=20,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("oven", "Oven (dark)"),
                            ("paper", "Paper (light)"),
                            ("espresso", "Espresso"),
                            ("sage", "Sage"),
                            ("custom", "Custom colours"),
                        ],
                        default="oven",
                        max_length=20,
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[("serif", "Elegant serif"), ("sans", "Modern sans")],
                        default="serif",
                        max_length=10,
                    ),
                ),
                ("background_color", models.CharField(blank=True, max_length=7)),
                ("text_color", models.CharField(blank=True, max_length=7)),
                ("accent_color", models.CharField(blank=True, max_length=7)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="menu-screens/"),
                ),
                (
                    "background_dim",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="How much the background photo is darkened, 0–90 %",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("rotate-right", "TV turned upright (rotate right)"),
                            ("rotate-left", "TV turned upright (rotate left)"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("de", "German"),
                            ("en", "English"),
                            ("ar", "Arabic"),
                            ("alternate", "German and English"),
                            ("de_ar", "German and Arabic"),
                        ],
                        default="de",
                        max_length=10,
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=120)),
                ("headline_en", models.CharField(blank=True, max_length=120)),
                ("headline_ar", models.CharField(blank=True, max_length=120)),
                (
                    "ticker",
                    models.CharField(
                        blank=True,
                        help_text="A running message along the bottom",
                        max_length=300,
                    ),
                ),
                ("ticker_en", models.CharField(blank=True, max_length=300)),
                ("ticker_ar", models.CharField(blank=True, max_length=300)),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Category ids in order; empty: all",
                    ),
                ),
                (
                    "featured_products",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Product ids for the large spot; empty: automatic",
                    ),
                ),
                ("hidden_products", models.JSONField(blank=True, default=list)),
                ("show_prices", models.BooleanField(default=True)),
                ("show_descriptions", models.BooleanField(default=True)),
                ("show_images", models.BooleanField(default=True)),
                ("show_tags", models.BooleanField(default=True)),
                ("show_qr", models.BooleanField(default=True)),
                ("show_clock", models.BooleanField(default=True)),
                ("show_status", models.BooleanField(default=True)),
                (
                    "sold_out",
                    models.CharField(
                        choices=[("mark", "Show as sold out"), ("hide", "Hide")],
                        default="mark",
                        max_length=10,
                    ),
                ),
                ("page_seconds", models.PositiveSmallIntegerField(default=12)),
                (
                    "slide_every",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Show a promotion after this many menu pages",
                    ),
                ),
                ("reload_token", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("photo", "Photo with text"),
                            ("product", "Product highlight"),
                            ("text", "Big message"),
                        ],
                        default="product",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                ("title_ar", models.CharField(blank=True, max_length=120)),
                ("text", models.CharField(blank=True, max_length=300)),
                ("text_en", models.CharField(blank=True, max_length=300)),
                ("text_ar", models.CharField(blank=True, max_length=300)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "price_note",
                    models.CharField(
                        blank=True, help_text='e.g. "instead of 5.40 €"', max_length=60
                    ),
                ),
                ("price_note_en", models.CharField(blank=True, max_length=60)),
                ("price_note_ar", models.CharField(blank=True, max_length=60)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="menu-screens/slides/"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "seconds",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Empty: the screen's page time", null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="0 = Monday; empty: every day",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="menuboard.menuscreen",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
