# Generated by Django 5.1.4 on 2026-09-30 16:35

from django.db import migrations, models


def keep_default_addresses(apps, schema_editor):
    # Addresses set as a customer's default address stay visible as saved.
    Address = apps.get_model('accounts', 'Address')
    Customer = apps.get_model('accounts', 'Customer')
    default_ids = Customer.objects.exclude(address__isnull=True).values_list('address_id', flat=True)
    Address.objects.filter(pk__in=list(default_ids)).update(saved=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="saved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(keep_default_addresses, migrations.RunPython.noop),
    ]
