# Generated by Django 5.1.4 on 2024-12-20 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customer"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cart",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="accounts.customer",
            ),
            preserve_default=False,
        ),
    ]
