# Generated by Django 5.1.4 on 2025-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Used for optimistic locking', verbose_name='Version'),
        ),
    ]
