# Generated by Django 5.1.4 on 2026-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_seasonal",
            field=models.BooleanField(
                default=False,
                help_text="Shown on the seasonal specials page",
                verbose_name="Seasonal",
            ),
        ),
    ]
