# Generated by Django 5.1.4 on 2026-09-30 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_bakery_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="Optional .glb model shown in the 3D viewer instead of the photo",
                null=True,
                upload_to="products/3d/",
                validators=[django.core.validators.FileExtensionValidator(["glb"])],
                verbose_name="3D model",
            ),
        ),
    ]
