# Generated by Django 5.1.4 on 2026-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_model_3d"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Name (English)"
            ),
        ),
    ]
